services:
  bot-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - config/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aditya123
      POSTGRES_DB: assignmnets_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
